version: "3"

services:
  postgres:
    image: postgres:14
    tty: true
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=webapp
    volumes:
    - /data/postgres2:/var/lib/postgresql/data
