version: "3"

services:
  webapp:
    build: ./deployment
    container_name: webapp
    restart: always
    environment:
      env_file: ../.env
    entrypoint: /webapp
    ports:
    - "8080:8080"
    - "50051:50051"
    networks:
    - kafka-net
    depends_on:
    - postgres

  postgres:
    image: postgres:14
    container_name: postgres
    tty: true
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=webapp
    volumes:
    - /data/postgres2:/var/lib/postgresql/data
    networks:
    - kafka-net

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
    - "2181:2181"
    networks:
    - kafka-net
  
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - kafka-net
    depends_on:
    - zookeeper

networks:
  kafka-net:
    driver: bridge
